using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditorInternal;
using UnityEngine;

namespace SaintsConst.Editor
{
    public static class GenerateLayers
    {

        public static void OnLoadWatch()
        {
            CheckChangeAndWrite();
        }

        private static void CheckChangeAndWrite()
        {
            const string savePath = Entrance.GenerateFolder + "/LayerConst.cs";

            StringBuilder nameFieldsBuilder = new StringBuilder();
            StringBuilder indexFieldsBuilder = new StringBuilder();
            StringBuilder maskFieldsBuilder = new StringBuilder();

            HashSet<string> conflictedSet = new HashSet<string>();

            foreach (LayerInfo layerInfo in GetFineLayers())
            {
                if (layerInfo.Conflicted)
                {
                    conflictedSet.Add(layerInfo.Name);
                }
                else
                {
                    nameFieldsBuilder.Append(string.Format(NameFieldTemplate, layerInfo.Key, layerInfo.Name));
                    indexFieldsBuilder.Append(string.Format(IndexFieldTemplate, layerInfo.Key, layerInfo.Index));
                    maskFieldsBuilder.Append(string.Format(MaskFieldTemplate, layerInfo.Key, layerInfo.Index));
                }
            }

            string conflictLine = "";
            if (conflictedSet.Count > 0)
            {
                conflictLine = $"\n        // WARNING: conflict layer mask name found: {string.Join(", ", conflictedSet)}\n\n";
            }

            string fileContent = string.Format(FileTemplate, conflictLine, nameFieldsBuilder, indexFieldsBuilder, maskFieldsBuilder);

            string oldFileContent = "";
            if (File.Exists(savePath))
            {
                oldFileContent = File.ReadAllText(savePath);
            }

            // ReSharper disable once InvertIf
            if (fileContent != oldFileContent)
            {
                Debug.Log($"Update content in {savePath}");
                File.WriteAllText(savePath, fileContent, Encoding.UTF8);
            }
        }

        private readonly struct LayerInfo
        {
            public readonly string Key;
            public readonly string Name;
            public readonly int Index;
            public readonly bool Conflicted;

            public LayerInfo(string key, string name, int index, bool conflicted)
            {
                Key = key;
                Name = name;
                Index = index;
                Conflicted = conflicted;
            }
        }

        private static IEnumerable<LayerInfo> GetFineLayers()
        {
            // List<(string, string)> results = new List<(string, string)>();
            HashSet<string> existsName = new HashSet<string>();

            for (int layer = 0; layer < 32; ++layer)
            {
                string layerName = InternalEditorUtility.GetLayerName(layer);
                if (layerName.Length != 0)
                {
                    string key = Utils.ProperVarName(layerName);
                    bool conflicted = !existsName.Add(key);
                    if(conflicted)
                    {
                        Debug.LogWarning($"Layer `{layerName}` has conflict programming name `{key}`, skip");
                    }

                    yield return new LayerInfo(key, layerName, layer, conflicted);
                }
            }

        }

        private const string FileTemplate = @"
// Generated by SaintsConst
// ReSharper disable once CheckNamespace
namespace SaintsConst
{{
    {0}
    public static class LayerConst
    {{
        public static class Name 
        {{
{1}
        }}
        public static class Index 
        {{
{2}
        }}
        public static class Mask 
        {{
{3}
        }}
    }}
}}
";

        private const string NameFieldTemplate = @"
            // ReSharper disable once InconsistentNaming
            public const string {0} = ""{1}"";
";
        private const string IndexFieldTemplate = @"
            /// <summary>
            /// {0} ({1})
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const int {0} = {1};
";
        private const string MaskFieldTemplate = @"
            /// <summary>
            /// {0} ({1})
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const int {0} = 1 << {1};
";
    }
}
