using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditorInternal;
using UnityEngine;

namespace SaintsConst.Editor
{
    public static class GenerateTags
    {
        public static void OnLoadWatch()
        {
            CheckChangeAndWrite();
        }

        private static void CheckChangeAndWrite()
        {
            const string savePath = Entrance.GenerateFolder + "/TagConst.cs";

            StringBuilder fieldsBuilder = new StringBuilder();

            HashSet<string> conflictedSet = new HashSet<string>();

            foreach ((string tagName, string tagValue, bool conflicted) in GetFineTags())
            {
                // Debug.Log($"{tagName}=>{tagValue}");
                if (conflicted)
                {
                    conflictedSet.Add(tagValue);
                    // fieldsBuilder.Append($"\n        // WARNING: conflict tag name found: {tagValue}\n\n");
                }
                else
                {
                    fieldsBuilder.Append(string.Format(FieldTemplate, tagName, tagValue));
                }
            }

            string conflictLine = "";
            if (conflictedSet.Count > 0)
            {
                conflictLine = $"\n        // WARNING: conflict tag name found: {string.Join(", ", conflictedSet)}\n\n";
            }

            string fileContent = string.Format(FileTemplate, $"{conflictLine}{fieldsBuilder}");

            string oldFileContent = "";
            if (File.Exists(savePath))
            {
                oldFileContent = File.ReadAllText(savePath);
            }

            if (fileContent != oldFileContent)
            {
                Debug.Log($"Update content in {savePath}");
                File.WriteAllText(savePath, fileContent, Encoding.UTF8);
            }
        }

        private static IEnumerable<(string tagName, string tagValue, bool conflicted)> GetFineTags()
        {
            // List<(string, string)> results = new List<(string, string)>();
            HashSet<string> existsName = new HashSet<string>();
            string[] curTags = InternalEditorUtility.tags;
            foreach (string tag in curTags)
            {
                string tagKey = Utils.ProperVarName(tag);
                if(existsName.Add(tagKey))
                {
                    yield return (tagKey, tag, false);
                }
                else
                {
                    Debug.LogWarning($"Tag `{tag}` has conflict programming name `{tagKey}`, skip");
                    yield return (tagKey, tag, true);
                }
            }
        }



        private const string FileTemplate = @"
// Generated by SaintsConst
// ReSharper disable once CheckNamespace
namespace SaintsConst
{{
    public static class TagConst
    {{
{0}
    }}
}}
";

        private const string FieldTemplate = @"
        /// <summary>
        /// {1}
        /// </summary>
        // ReSharper disable once InconsistentNaming
        public const string {0} = ""{1}"";
";
    }
}
