using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditorInternal;
using UnityEngine;

namespace SaintsConst.Editor
{
    public class GenerateRenderingLayers
    {

        public static void OnLoadWatch()
        {
            CheckChangeAndWrite();
        }

        private static void CheckChangeAndWrite()
        {
            const string savePath = Entrance.GenerateFolder + "/RenderingLayerConst.cs";

            StringBuilder fieldsBuilder = new StringBuilder();

            HashSet<string> conflictedSet = new HashSet<string>();

            foreach ((string layerName, uint layerValue, bool conflicted) in GetFineTags())
            {
                if (conflicted)
                {
                    conflictedSet.Add(layerName);
                }
                else
                {
                    fieldsBuilder.Append(string.Format(FieldTemplate, layerName, layerValue));
                }
            }

            string conflictLine = "";
            if (conflictedSet.Count > 0)
            {
                conflictLine = $"\n        // WARNING: conflict layer mask name found: {string.Join(", ", conflictedSet)}\n\n";
            }

            string fileContent = string.Format(FileTemplate, $"{conflictLine}{fieldsBuilder}");

            string oldFileContent = "";
            if (File.Exists(savePath))
            {
                oldFileContent = File.ReadAllText(savePath);
            }

            if (fileContent != oldFileContent)
            {
                Debug.Log($"Update content in {savePath}");
                File.WriteAllText(savePath, fileContent, Encoding.UTF8);
            }
        }

        private static IEnumerable<(string key, uint mask, bool conflicted)> GetFineTags()
        {
            // List<(string, string)> results = new List<(string, string)>();
            HashSet<string> existsName = new HashSet<string>();

            foreach (string name in RenderingLayerMask.GetDefinedRenderingLayerNames())
            {
                uint mask = RenderingLayerMask.GetMask(name);
                string key = Utils.ProperVarName(name);
                if(existsName.Add(key))
                {
                    yield return (key, mask, false);
                }
                else
                {
                    Debug.LogWarning($"Rendering Layer `{name}` has conflict programming name `{key}`, skip");
                    yield return (key, mask, true);
                }
            }
        }

        private const string FileTemplate = @"
// Generated by SaintsConst
// ReSharper disable once CheckNamespace
namespace SaintsConst
{{
    [System.Flags]
    public enum RenderingLayerConst: uint
    {{
{0}
    }}
}}
";

        private const string FieldTemplate = @"
        /// <summary>
        /// {0} ({1})
        /// </summary>
        // ReSharper disable once InconsistentNaming
        {0} = {1},
";
    }
}
