using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditorInternal;
using UnityEngine;

namespace SaintsConst.Editor
{
    public static class GenerateLayers
    {

        public static void OnLoadWatch()
        {
            CheckChangeAndWrite();
        }

        private static void CheckChangeAndWrite()
        {
            const string savePath = Entrance.GenerateFolder + "/LayerConst.cs";

            StringBuilder fieldsBuilder = new StringBuilder();

            HashSet<string> conflictedSet = new HashSet<string>();

            foreach ((string layerName, int layerValue, bool conflicted) in GetFineTags())
            {
                if (conflicted)
                {
                    conflictedSet.Add(layerName);
                }
                else
                {
                    fieldsBuilder.Append(string.Format(FieldTemplate, layerName, layerValue));
                }
            }

            string conflictLine = "";
            if (conflictedSet.Count > 0)
            {
                conflictLine = $"\n        // WARNING: conflict layer mask name found: {string.Join(", ", conflictedSet)}\n\n";
            }

            string fileContent = string.Format(FileTemplate, $"{conflictLine}{fieldsBuilder}");

            string oldFileContent = "";
            if (File.Exists(savePath))
            {
                oldFileContent = File.ReadAllText(savePath);
            }

            if (fileContent != oldFileContent)
            {
                Debug.Log($"Update content in {savePath}");
                File.WriteAllText(savePath, fileContent, Encoding.UTF8);
            }
        }

        private static IEnumerable<(string layerName, int layerMask, bool conflicted)> GetFineTags()
        {
            // List<(string, string)> results = new List<(string, string)>();
            HashSet<string> existsName = new HashSet<string>();

            for (int layer = 0; layer < 32; ++layer)
            {
                string layerName = InternalEditorUtility.GetLayerName(layer);
                if (layerName.Length != 0)
                {
                    string key = Utils.ProperVarName(layerName);
                    if(existsName.Add(key))
                    {
                        yield return (key, layer, false);
                    }
                    else
                    {
                        Debug.LogWarning($"Layer `{layerName}` has conflict programming name `{key}`, skip");
                        yield return (key, layer, true);
                    }
                }
            }

        }

        private const string FileTemplate = @"
// Generated by SaintsConst
// ReSharper disable once CheckNamespace
namespace SaintsConst
{{
    public static class LayerConst
    {{
{0}
    }}
}}
";

        private const string FieldTemplate = @"
        /// <summary>
        /// {0} ({1})
        /// </summary>
        // ReSharper disable once InconsistentNaming
        public const int {0} = 1 << {1};
";
    }
}
