using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditorInternal;
using UnityEngine;

namespace SaintsConst.Editor
{
    public class GenerateSortingLayers
    {
        public static void OnLoadWatch()
        {
            CheckChangeAndWrite();
        }

        private static void CheckChangeAndWrite()
        {
            const string savePath = Entrance.GenerateFolder + "/SortingLayerConst.cs";

            StringBuilder nameBuilder = new StringBuilder();
            StringBuilder idBuilder = new StringBuilder();

            List<SortingLayerInfo> conflictedSet = new List<SortingLayerInfo>();

            foreach (SortingLayerInfo info in GetFineSortingLayers())
            {
                if (info.Conflicted)
                {
                    conflictedSet.Add(info);
                }
                else
                {
                    nameBuilder.Append(string.Format(NameTemplate, info.Key, info.Name));
                    idBuilder.Append(string.Format(IdTemplate, info.Key, info.Id));
                }
            }

            string conflictLine = "";
            if (conflictedSet.Count > 0)
            {
                conflictLine = $"\n        // WARNING: conflict tag name found: {string.Join(", ", conflictedSet)}\n\n";
            }

            string fileContent = string.Format(FileTemplate, conflictLine, nameBuilder, idBuilder);

            string oldFileContent = "";
            if (File.Exists(savePath))
            {
                oldFileContent = File.ReadAllText(savePath);
            }

            if (fileContent != oldFileContent)
            {
                Debug.Log($"Update content in {savePath}");
                File.WriteAllText(savePath, fileContent, Encoding.UTF8);
            }
        }

        public readonly struct SortingLayerInfo
        {
            public readonly string Key;
            public readonly string Name;
            public readonly int Id;
            public readonly bool Conflicted;

            public SortingLayerInfo(string key, string name, int id, bool conflicted)
            {
                Key = key;
                Name = name;
                Id = id;
                Conflicted = conflicted;
            }
        }

        private static IEnumerable<SortingLayerInfo> GetFineSortingLayers()
        {
            // List<(string, string)> results = new List<(string, string)>();
            HashSet<string> existsName = new HashSet<string>();
            foreach (SortingLayer sl in SortingLayer.layers)
            {
                string name = sl.name;
                int id = sl.id;

                string key = Utils.ProperVarName(name);
                SortingLayerInfo result = new SortingLayerInfo(key, name, id, !existsName.Add(key));
                yield return result;
            }
        }



        private const string FileTemplate = @"
// Generated by SaintsConst
// ReSharper disable once CheckNamespace
namespace SaintsConst
{{
    {0}
    public static class SortingLayerConst
    {{

        public static class Name
        {{
            {1}
        }}

        public static class Id
        {{
            {2}
        }}

    }}
}}
";

        private const string NameTemplate = @"
            /// <summary>
            /// {0} ({1})
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const string {0} = ""{1}"";
";
        private const string IdTemplate = @"
            /// <summary>
            /// {0} ({1})
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const int {0} = {1};
";
    }
}
